### ISSUE TITLE
Inception-Risk List and Management Plan– Describe risks (business, technical, resource, schedule)

### ISSUE THREAD

**Issue by batmannolove** [batmannolove/Android-Client-Server-Distributed-Socket-Public#6]
Risk List and Management Plan– Describe risks (business, technical, resource, schedule)
SYT

**Comment by Esther12** [comment]
[risk management.docx](https://github.com/batmannolove/Android-Client-Server-Distributed-Socket-Public/files/794577/risk.management.docx)

**Comment by Esther12** [comment]
[UP setps&artifacts.docx](https://github.com/batmannolove/Android-Client-Server-Distributed-Socket-Public/files/800429/UP.setps.artifacts.docx)
